[phases.setup]
nixPkgs = [
    "python3",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "libxcomposite",
    "libxdamage",
    "libxfixes",
    "libxrandr",
    "mesa",
    "pango",
    "alsa-lib"
]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[start]
cmd = "streamlit run main.py --server.port=$PORT --server.address=0.0.0.0"